#!/usr/bin/env bash

set -x

./plum/rime-install packages.conf

rm custom_phrase.txt
rm default.yaml
rm double_pinyin.schema.yaml
rm double_pinyin_abc.schema.yaml
rm double_pinyin_flypy.schema.yaml
rm double_pinyin_mspy.schema.yaml
rm double_pinyin_sogou.schema.yaml
rm double_pinyin_ziguang.schema.yaml
rm squirrel.yaml
rm t9.schema.yaml
rm weasel.yaml

# Keep
# melt_eng.dict.yaml
# melt_eng.schema.yaml
# radical_pinyin.dict.yaml
# radical_pinyin.schema.yaml
# rime.lua
# rime_ice.dict.yaml
# rime_ice.schema.yaml
# symbols_caps_v.yaml
# symbols_v.yaml
